const translations = {
    "en": {
        "welcomeMsg": "Welcome to Furniture World",
        "introText": "Discover our exclusive collection of furniture and home accessories...",
        "titleView": "Home - Furniture World",
        "homeView" : "Home",
        "aboutView": "About the Company",
        "catalogView" : "Catalog",
        "promotionView" : "Promotion",
        "contactsView" : "Contacts",
        "siteView" : "Site Author",
        "testimonialsView": "Testimonials/Review",
        "copyView": "2024 Furniture World. All rights reserved.",
        "teoView": "2024 Teodora Galinova Vasileva",
        "aboutfwView": "About Furniture World",
        "withsView": "With sun in the heart to number 1 in the world!",
        "withs1View": "This is our philosophy at Furniture World. Our team goes about their daily work with strength, joy, and endurance, aiming to be number 1 in their field.",
        "withs2View": "How We Think",
        "withs3View": "The customer is king: At Furniture World, customer satisfaction is paramount. This includes an excellent price- quality ratio, a pleasant shopping atmosphere, professional advice, and modern logistics.",
        "withs4View": "Sustainable Development: We support environmental actions in all areas, focusing on the economical use of resources and adherence to environmental standards.",
        "withs5View": "Figures and Facts",
        "withs6View": "Our group operates in 13 countries with over 320 stores in Europe and employs 25,700 associates. With a turnover of over €5.1 billion, we're one of the largest furniture retailers in the world.",
        "withs7View":"Our History",
        "withs8View": "Founded in 1993 in Sofia, Furniture World has grown from a small 15 square meter store to the largest furniture store in Bulgaria, with several key milestones and expansions along the way.",
        "withs9View": "Significant developments include the opening of our largest store in Sofia in 2006, the construction of a logistics center in 2008, marking a new era of growth and stability.",
        "withs10View": "Looking to the Future",
        "withs11View": "As we continue to expand and innovate, our commitment to customer satisfaction and environmental responsibility remains at the forefront of our mission.",
        "title1View": "About The Company",
        "title2View": "Catalog - Furniture World",
        "catalogView": "Our Catalog",
        "livingView": "Living Room",
        "living1View": "Elegant Living Room Set",
        "living2View": "A sophisticated and stylish living room set that brings modern elegance to your home.",
        "living3View": "Price: $1,200",
        "living4View": "Contemporary Dining Room Set",
        "living5View": "Perfect for family dinners, this dining set combines style and functionality.",
        "living6View": "Price: $850",
        "living7View": "Back to Top",
        "living8View": "Bedroom",
        "living9View": "Modern Bedroom Set",
        "living10View": "A luxurious bedroom set that offers comfort and a touch of elegance.",
        "living11View": "Price: $1,500",
        "living12View": "Luxurious Home Office Set",
        "living13View": "Transform your workspace with this modern, sophisticated home office furniture.",
        "living14View": "Price: $1,100",
        "living15View": "Outdoor & Kids",
        "living16View": "Stylish Outdoor Patio Set",
        "living17View": "Elevate your outdoor space with this chic and comfortable patio set.",
        "living18View": "Price: $950",
        "living19View": "Kids' Bedroom Set",
        "living20View": "A colorful and playful furniture set that will light up any child's room.",
        "living21View": "Price: $700",
        "title3View": "Promotion - Furniture World",
        "promotionView": "Current Promotions",
        "promotion1View": "Spring Sale: Up to 50% Off!",
        "promotion2View": "Get amazing discounts on select furniture items this spring. Hurry, offer valid while stocks last!",
        "promotion3View": "Shop Now",
        "promotion4View":"New Arrivals: Exclusive 20% Discount",
        "promotion5View": "Explore our new collection of modern furniture and enjoy an exclusive 20% introductory discount.",
        "promotion6View": "Discover More",
        "title4View": "Contact Us - Furniture World",
        "contactView": "Contact Us",
        "contact1View": "If you have any questions, please feel free to reach out to us.",
        "contact2View": "Name:",
        "contact3View": "Email:",
        "contact4View": "Message:",
        "contact5View": "Other Ways to Reach Us",
        "contact6View": "Phone:",
        "contact7View": "Address:",
        "contact8View": "Ignatievo,Varna,Bulgaria",
        "title5View": "About the Author - Furniture World",
        "authorView": "About the Author",
        "author1View": "Teodora Galinova Vasileva",
        "author2View": "Teodora Galinova Vasileva, an 18-year-old student from Varna, is an emerging talent in the field of electronic commerce. Studying at High School St.Kliment Ohridski in Aksakovo, she has developed a profound understanding of the digital marketplace through her academic work.Her passion lies at the intersection of technology and consumer engagement, where she aims to innovate and enhance online shopping experiences.With a forward- thinking mindset, Teodora represents the bright future of e- commerce in Bulgaria and beyond.",
        "title6View": "Testimonials - Furniture World",
        "testimonialView": "Customer Testimonials",
        "testimonial1View": "Furniture World transformed our living room with their elegant designs.We couldn't be happier with the quality and comfort of the furniture we purchased.",
        "testimonial2View": "— John Doe, Varna",
        "testimonial3View": "The customer service at Furniture World is top-notch. They helped me select the perfect bedroom set, and the delivery was seamless and on time.",
        "testimonial4View": "— Jane Smith, Sofia"
        
        // ... other translations
    },
    "bg": {
        "welcomeMsg": "Добре дошли в Мебелен свят",
        "introText": "Открийте нашата ексклузивна колекция от мебели и аксесоари за дома...",
        "titleView": "Начало - Мебелен свят",
        "homeView": "Начало",
        "aboutView": "За компанията",
        "catalogView": "Каталог",
        "promotionView": "Промоция",
        "contactsView": "Контакти",
        "siteView": "Автор на сайта",
        "testimonialsView": "Свидетелства/Отзиви",
        "copyView": "2024 Мебелен свят. Всички права запазени.",
        "teoView": "2024 Теодора Галинова Василева.",
        "aboutfwView": "Относно Мебелен свят",
        "withsView": "Със слънце в сърцето към номер 1 в света!",
        "withs1View": "Това е философията ни в Мебелен свят.Нашият екип извършва своята дневна работа със сила, радост и издръжливост, с цел да бъде номер 1 в своята област.",
        "withs2View": "Как мислим",
        "withs3View": "Клиентът е цар: В Мебелен свят, удовлетворението на клиента е от първостепенно значение. Това включва отлично съотношение цена-качество, приятна атмосфера за пазаруване, професионални съвети и модерна логистика.",
        "withs4View": "Устойчиво развитие: Подкрепяме екологични действия във всички области, акцентирайки върху икономичното използване на ресурси и спазването на екологични стандарти.",
        "withs5View": "Цифри и Факти",
        "withs6View": "Нашата група оперира в 13 държави с над 320 магазина в Европа и има 25 700 служители. С оборот над 5,1 милиарда евро, сме един от най-големите търговци на мебели в света.",
        "withs7View": "Нашата История",
        "withs8View": "Основана през 1993 г. в София, Мебелен свят се разраства от малък магазин с площ от 15 квадратни метра до най-големия магазин за мебели в България, като преминава през няколко ключови стъпки и разширения по пътя.",
        "withs9View": "Значителни развития включват отварянето на нашия най-големи магазин в София през 2006 г. и изграждането на логистичен център през 2008 г., което означава нов етап от растеж и стабилност.",
        "withs10View": "Гледайки към Бъдещето",
        "withs11View": "Докато продължаваме да се разширяваме и иновираме, нашата ангажираност към удовлетворението на клиентите и отговорността към околната среда остават в основата на нашата мисия.",
        "title1View": "За Компанията",
        "title2View": "Каталог - Мебелен свят",
        "catalogView": "Ншият Каталог",
        "livingView": "Дневна стая",
        "living1View": "Елегантен комплект за дневната стая",
        "living2View": "Софистикиран и стилен комплект за дневната стая, който носи съвременна елегантност у дома ви.",
        "living3View": "Цена: $1,200",
        "living4View": "Съвремен комплект за трапезария",
        "living5View": "Перфектен за семейни вечери, този комплект за трапезария комбинира стил и функционалност.",
        "living6View": "Цена: $850",
        "living7View": "Горе",
        "living8View": "Спалня",
        "living9View": "Модерен комплект за спалня",
        "living10View": "Луксозен комплект за спалня, който предлага комфорт и докосване на елегантност.",
        "living11View": "Цена: $1,500",
        "living12View": "Луксозен комплект за домашен офис",
        "living13View": "Преобразете работното си пространство с този модерен и изискан мебелен комплект за домашен офис.",
        "living14View": "Цена: $1,100",
        "living15View": "Открито пространство и детски стаи",
        "living16View": "Стилен комплект за външен патио",
        "living17View": "Повишете стилът и комфорта на вашия външен пространство с този елегантен и удобен комплект за патио.",
        "living18View": "Цена: $950",
        "living19View": "Детски комплект за спалня",
        "living20View": "Цветен и игрив комплект мебели, който ще освети всяка детска стая.",
        "living21View": "Цена: $700",
        "title3View": "Промоция - Мебелен свят",
        "promotionView": "Текущи промоции",
        "promotion1View": "Пролетна разпродажба: До 50% отстъпка!",
        "promotion2View": "Вземете невероятни отстъпки на избрани мебели това пролет. Побързайте, офертата е валидна до изчерпване на количествата!",
        "promotion3View": "Пазарувайте сега",
        "promotion4View": "Нови пристигания: Ексклузивна отстъпка от 20%",
        "promotion5View": "Разгледайте нашата нова колекция от модерни мебели и се възползвайте от ексклузивна въведенска отстъпка от 20%.",
        "promotion6View": "Открийте повече",
        "title4View": "Свържете се с нас - Мебелен свят",
        "contactView": "Свържете се с нас",
        "contact1View": "Ако имате въпроси, моля, не се колебайте да се свържете с нас.",
        "contact2View": "Име:",
        "contact3View": "Имейл:",
        "contact4View": "Съобщение:",
        "contact5View": "Други начини за свързване с нас",
        "contact6View": "Телефон:",
        "contact7View": "Адрес:",
        "contact8View": "Игнатиево, Варна, България",
        "title5View": "За автора - Мебелен свят",
        "authorView": "За автора",
        "author1View": "Теодора Галинова Василева",
        "author2View": "Теодора Галинова Василева, 18-годишна студентка от Варна, е развиващ се талант в областта на електронната търговия. Учейки в Средно училище „Свети Климент Охридски“ в Аксаково, тя разви дълбоко разбиране за цифровия пазар чрез академичната си работа. Нейната страст лежи на кръстопътя между технологията и ангажираността на потребителите, където цели да иновира и подобри онлайн преживяванията при пазаруване. Със свой съобразителен ум, Теодора представлява светлото бъдеще на електронната търговия в България и извън нея.",
        "title6View": "Отзиви - Мебелен свят",
        "testimonialView": "Отзиви от клиенти",
        "testimonial1View": "Мебелен свят преобрази стаята ни с елегантните си дизайни. Не можем да бъдем по-щастливи от качеството и комфорта на мебелите, които закупихме.",
        "testimonial2View": "— Джон Доу, Варна",
        "testimonial3View": "Обслужването на клиенти в Мебелен свят е на високо ниво. Те ми помогнаха да избера перфектния комплект за спалня, а доставката беше безпроблемна и навременна.",
        "testimonial4View": "— Джейн Смит, София"
        // ... other translations
    }
};

let currentLang = 'en';

function switchLanguage() {
    currentLang = currentLang === 'en' ? 'bg' : 'en';
    document.getElementById("langSwitch").textContent = currentLang === 'en' ? "EN" : "BG";
    document.getElementById("langSwitch").classList.toggle('active');
    document.querySelectorAll("[data-translate-key]").forEach(el => {
        const key = el.getAttribute("data-translate-key");
        el.textContent = translations[currentLang][key];
    });
}

document.addEventListener("DOMContentLoaded", function () {
    const langSwitchButton = document.getElementById("langSwitch");
    langSwitchButton.addEventListener("click", switchLanguage);

    // Initialize button appearance based on current language
    langSwitchButton.textContent = currentLang === 'en' ? "EN" : "BG";
    if (currentLang === 'bg') {
        langSwitchButton.classList.add('active');
    }
});